name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
    - master
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # https://github.com/golangci/golangci-lint-action/issues/535
          version: v1.47.3
          only-new-issues: true
